---
- name: Installing prometheus
  ansible.builtin.include_role:
    name: andrewrothstein.prometheus_installer
  vars:
    prometheus_installer_versions:
      - name: prometheus
        version: '{{ prometheus_ver }}'
